/*
 * Generated By Spring Data JPA Entity Generator
 * @author Niroshan Mendis
 */

package com.chamith.employeems.entity;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.util.List;

@Data
@Entity
@NoArgsConstructor
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class Skill {

    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    private Integer id;

    @NotNull(message="Name is required")
    @Size(min=0, max=10, message="Maximum character count is 10")
    private String name;

    @JsonIgnore
    @ManyToMany(mappedBy = "skillList")
    private List<Employee> employeeList;

    @JsonIgnore
    @OneToMany(mappedBy="nametitle")
    private List<BasicEmployee> basicEmployeeList;


    public Skill(Integer id){
        this.id = id;
    }


}
